version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev.yml
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev.yml
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

